In [1]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5,4)
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [3]:
ind = data.argmax(axis = 0)
ind # array([2, 0, 3, 1]

array([2, 0, 3, 1], dtype=int64)

In [11]:
data.shape,
data[ind]

array([[ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]])

In [6]:
data_max = data[ind, range(data.shape[1])] # data[행, 열]
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [9]:
data[[2,0,3,1],range(data.shape[1])] # data[[2,0,3,1]] => 데이터의 재정렬이 일어남.(고급인덱싱)
                                                        # [최대 a a a]
                                                        # [a 최대 a a]
                                                        # [a a 최대 a]
                                                        # [a a a 최대]
                                                        # 위와 같은 형태로 만들어주기 때문에 range(shape[1])범위를 순회하면 최대값을 구할 수 있음

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])