In [2]:
import numpy as np
a = np.random.normal(1,10,(2,5))
a

array([[24.3040286 , -4.34391177, 14.89776722, -4.53420182, 14.00347036],
       [-9.46877525, 12.69145644, -3.90675109, -6.88159421, 10.71270609]])

In [5]:
a.std(axis=0), a.std(axis=1)

(array([16.88640192,  8.51768411,  9.40225916,  1.1736962 ,  1.64538214]),
 array([11.44705832,  9.23180493]))

In [7]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
b = np.arange(11,21).reshape(2,-1)
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
a+b

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [10]:
a-b

array([[-11, -11, -11, -11, -11],
       [-11, -11, -11, -11, -11]])

In [12]:
a*b

array([[  0,  12,  26,  42,  60],
       [ 80, 102, 126, 152, 180]])

In [13]:
a%b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
a[:,3:]

array([[3, 4],
       [8, 9]])

In [19]:
np.linalg.inv(a@a.T)

array([[ 0.204, -0.064],
       [-0.064,  0.024]])

In [28]:
a = np.arange(10).reshape(2,-1)
b = np.arange(11,21).reshape(2,-1)
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [30]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [31]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
np.dstack((a,b))

array([[[ 0, 11],
        [ 1, 12],
        [ 2, 13],
        [ 3, 14],
        [ 4, 15]],

       [[ 5, 16],
        [ 6, 17],
        [ 7, 18],
        [ 8, 19],
        [ 9, 20]]])

In [33]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
a = np.array([1,2,3,4])
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [37]:
# quiz a = np.arange(20).reshape(5,4)의 마지막 행의 데이터를 2차원으로 변경(4열 -> 4행 1열)
## a[-1] -> 1개 행만 가져와 // a[-1:] -> 마지막행 부터 마지막행까지 다 가져와 -> 2차원이면 열에 대한 정보가 있어서 2차원 반환
a = np.arange(20).reshape(5,4)

In [40]:
a = np.arange(10).reshape(2,-1)
b = np.arange(11,21).reshape(2,-1)
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [41]:
np.stack((a,b),axis=0)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [48]:
a = np.arange(10)
b = np.arange(11,21)
np.stack((a,b),axis=-1) # stack => 차원이 1개 증가한 상태이며 -1을 하면 2차원에서 1축을 선택하게 되고 이에따라 아래와 같이 나옴

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 5, 16],
       [ 6, 17],
       [ 7, 18],
       [ 8, 19],
       [ 9, 20]])

In [47]:
np.dstack((a,b))

array([[[ 0, 11],
        [ 1, 12],
        [ 2, 13],
        [ 3, 14],
        [ 4, 15],
        [ 5, 16],
        [ 6, 17],
        [ 7, 18],
        [ 8, 19],
        [ 9, 20]]])

In [51]:
a = np.array([1])
b = np.array([2])
np.dstack(a)

array([[[1]]])